version: '3.0'
services:
  mysql:
    container_name: order_service_db
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "order_service"
      MYSQL_ROOT_PASSWORD: "123456789"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql/init-db.sql:/docker-entrypoint-initdb.d/init-database-test.sql

  order:
    container_name: order-service
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    build: .
    environment:
      profile: "docker"

volumes:
  mysql:
    driver: local

